{{- if and .Values.gateway.auth.token (not .Values.gateway.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remedik.gatewayTokenSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remedik.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.gateway.auth.secretKey }}: {{ .Values.gateway.auth.token | quote }}
{{- end }}
{{- if and .Values.dashboard.enabled .Values.dashboard.auth.token (not .Values.dashboard.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remedik.dashboardTokenSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remedik.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.dashboard.auth.secretKey }}: {{ .Values.dashboard.auth.token | quote }}
{{- end }}
